[project]
name = "odoo-addons-oca-manufacture"
version = "18.0.20241126.0"
dependencies = [
    "odoo-addon-mrp_warehouse_calendar==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
